### ISSUE TITLE
Cannot reproduce Robust Optimal Transport

### ISSUE THREAD

**Issue by ootts** [uncbiag/shapmagn#3]
Hi, thanks for your work!

I just had a try of the [Robust Optimal Transport](https://github.com/uncbiag/shapmagn/blob/master/shapmagn/demos/ot_fun.py).
But the results are different from the provided GIF.
Some keyframes are as below:
![image](https://github.com/uncbiag/shapmagn/assets/24546823/e1492c15-bb73-47d6-94fe-3e6d8aad8e31)
![image](https://github.com/uncbiag/shapmagn/assets/24546823/b5a95133-dd52-4785-afe6-0fbb94aac4e4)
![image](https://github.com/uncbiag/shapmagn/assets/24546823/620ee2b3-9486-4793-bec1-59c0b5b082b5)
![image](https://github.com/uncbiag/shapmagn/assets/24546823/df668668-1919-45bd-bd5f-f5f4a0209e74)

**Comment by hbgtjxzbbx** [comment]
thanks for the report. seems the default settings is not good.  set blur =0.001 should work.
